Sample code change for Routing/Account Number
AuthorizeNet/sample-code-csharp pull request #74
Opened 2018-08-10 14:11 UTC by saikatbasu01

Random generation of Account Number logic added as DebitBankAccount sample code starts failing if the same account number-routing number combination is used multiples times.

2018-08-13 15:59 UTC, ashtru requested changes

2018-08-13 15:59 UTC, ashtru commented on CustomerProfiles/CreateCustomerProfile.cs
> +                expirationDate  = "0719"
Change it to 0728. Wherever you see 2018, increased it by 10 years.

2018-08-13 15:59 UTC, ashtru commented on CustomerProfiles/UpdateCustomerPaymentProfile.cs
> +                expirationDate = "0719"
Change it to 0728. Wherever you see 2018, increased it by 10 years.

2018-08-13 15:59 UTC, ashtru commented on CustomerProfiles/UpdateCustomerShippingAddress.cs
> +                 expirationDate = "0719"
Change it to 0728. Wherever you see 2018, increased it by 10 years.

2018-08-13 15:59 UTC, ashtru commented on PaymentTransactions/AuthorizeCreditCard.cs
> +                expirationDate  = "0719"
Change it to 0728. Wherever you see 2018, increased it by 10 years.

2018-08-13 15:59 UTC, ashtru commented on PaymentTransactions/ChargeTokenizedCreditCard.cs
> +                expirationDate = "0719",
Change it to 0728. Wherever you see 2018, increased it by 10 years.

2018-08-13 15:59 UTC, ashtru commented on PaymentTransactions/DebitBankAccount.cs
> +            int randomAccountNumber = rand.Next(100000000, int.MaxValue);
Starting can be 5-digit number. 
Test and verify locally once for 10000.

2018-08-13 15:59 UTC, ashtru commented on RecurringBilling/CreateSubscription.cs
> +                expirationDate  = "0719"
Change it to 0728. Wherever you see 2018, increased it by 10 years.

2018-08-13 15:59 UTC, ashtru commented on RecurringBilling/CreateSubscriptionFromCustomerProfile.cs
> +                expirationDate  = "0719"
Change it to 0728. Wherever you see 2018, increased it by 10 years.

2018-08-13 15:59 UTC, ashtru commented on RecurringBilling/UpdateSubscription.cs
> +                expirationDate = "0719"
Change it to 0728. Wherever you see 2018, increased it by 10 years.

2018-08-14 12:21 UTC, saikatbasu01 commented
Changes are modified as per review comments.

2018-09-20 19:12 UTC, merged

2018-09-20 19:19 UTC, ashtru commented
@saikatbasu01 
Good work on making the changes!
Just take care of whitespaces changes next time. I did a follow-up [commit ](https://github.com/AuthorizeNet/sample-code-csharp/commit/ca47e558071c84adfd004041b38be6ab3d2a1673)this time.